### ISSUE TITLE
progress bar as video is being indexed

### ISSUE THREAD

**Issue by zevav** [BTV-Python/gighacks-2015#30]

**Comment by marksibrahim** [comment]
loading status added with jQuery trigger

**Comment by zevav** [comment]
!!!

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com

**Comment by solumos** [comment]
:+1: :+1: :+1:

**Comment by zevav** [comment]
I'm not seeing a progress bar.  I think maybe this didn't get merged?
